a:a.cpp
	rm -f a
	g++ -std=c++11 a.cpp -o a
b:b.cpp
	g++ -std=c++11 b.cpp -o b
c:c.cpp
	g++ -std=c++11 c.cpp -o c
d:d.cpp
	g++ -std=c++11 d.cpp -o d
e:e.cpp
	g++ -std=c++11 e.cpp -o e
f:f.cpp
	g++ -std=c++11 f.cpp -o f

clean:
	rm a b c d e f
