a:a.cpp
	rm -f a
	g++ -std=c++14 a.cpp -o a
b:b.cpp
	rm -f b
	g++ -std=c++14 b.cpp -o b
c:c.cpp
	rm -f c
	g++ -std=c++14 c.cpp -o c
d:d.cpp
	rm -f d
	g++ -std=c++14 d.cpp -o d
e:e.cpp
	rm -f e
	g++ -std=c++14 e.cpp -o e
f:f.cpp
	rm -f f
	g++ -std=c++14 f.cpp -o f

clean:
	rm a b c d e f
